# Spring Tips: Liquibase

## Getting Started with Postgres

Before we can do anything, we'll need a valid PostgreSQL database to which we can connect.
You can run a Postgres instance in a Docker image. We'll need more than one database to develop, to simulate
`development` and `staging` builds, for example. I have this handy little script that quickly spins up
dummy PostgreSQL instances. Put this in a file called `postgres.sh`, and don't forget to run `chmod a+x postgres.sh`
to make it executable.

.postgres.sh
[source,shell,indent=0]
----
#!/usr/bin/env bash

NAME=${1}-postgres
PORT=${2:-5432}

docker run --name  $NAME  \
	-p ${PORT}:5432 \
	-e POSTGRES_USER=user \
	-e PGUSER=user \
	-e POSTGRES_PASSWORD=pw \
	postgres:latest

----

You can use it thusly:

[source,shell,indent=0]
----
./postgres.sh dev 5433
----

This will spin up an instance of the PostgreSQL Docker image called `dev-postgres` and run it on port `5433`.
If you don't specify a port, it'll use the default of `5432`. The username is `user` and the password is `pw`.
You can connect to the instance using the `psql` CLI, thusly:

[source,indent=0,shell]
----
psql -U user -h localhost -p 5433 dev
----

## Getting Started

You've probably probably got a database against which you want to start.
So, you'll want to use that as a starting spot. Configure the Apache Maven build to
use the `liquibase-maven-plugin`:

[source,indent=0,xml]
----
<plugin>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-maven-plugin</artifactId>
    <version>4.5.0</version>
    <configuration>
        <propertyFile>
            src/main/resources/liquibase.properties
        </propertyFile>
    </configuration>
</plugin>
----

Once you've got that, specify a file called `src/main/resources/liquibase.properties`. In it, put:

[source,indent=0,properties]
----
url=jdbc:postgresql://localhost/user
username=user
password=pw
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/generated.xml
----


Liquibase works by applying changelogs to the database. If you already have some schema,
then you need to create a changelog from that schema and use that as the first
version of your change sets. You can derive the bootstrap from the live schema, using the
Apache Maven plugin, like this:

[source,shell]
----
mvn liquibase:generateChangeLog
----

This will create a changelog in the file, `src/main/resources/db/changelog/generated.xml`. You can inspect it. We'll use
this to create our first changelog instance, called `src/main/resources/db/changelog/changelog-v1.0.xml`. Rename
`generated.xml` to `src/main/resources/db/changelog/changelog-v1.0.xml`. Spring Boot will automatically run the
changelog in our `src/main/resources/db/changelog/db.changelog-master.xml`, so let's include `changelog-v1.0.xml` from
`db.changelog-master.xml`.

[source,xml,indent=0]
----
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">
   <include file="db/changelog/changelog-v1.0.xml"/>
</databaseChangeLog>
----

The Maven plugin uses the connection information in `src/main/resources/liquibase.properties` to read the schema.
When you start your Spring Boot application, Liquibase will consult the meta database tables and run the as-yet unapplied
changelogs to the `javax.sql.DataSource` in your application.


## Making a Change

Let's suppose we want to evolve the database schema, perhaps by adding a new column. Create a new file,
`src/main/resources/db/changelog/changelog-v1.1.xml` with the following contents:


[source,xml,indent=0]
----
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

    <changeSet author="jlong" id="2022022105452668229700">
        <addColumn tableName="articles">
            <column name="published" type="timestamp"/>
        </addColumn>
    </changeSet>

</databaseChangeLog>
----

Here, we're using one of the Liquibase commands, `addColumn`, to add a column to a table. We can write these changesets
by hand, one at a time, but it's also very convenient to let Liquibase derive the delta between a database, say your
working database, and a checkpoint baseline schema. This way, you can guarantee you capture all changes since
your last deployment. We'll use the Maven plugin to do this. But you need to add some properties to your
`liquibase.properties` to account for both the old and the new schema.

[source,indent=0,properties]
----
url=jdbc:postgresql://localhost/user
username=user
password=pw
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/generated.xml
----


## Initializing a Bean Only After the Application's `DataSource` Has Been Initialized

You may have work that you want to execute after the Spring Boot application has started up and _after_ the Liquibase
database migration has finished. Annotate the bean with `@DependsOnDatabaseInitialization`, like this:

[source,java,indent=0]
----
    @Bean
    @DependsOnDatabaseInitialization
    ApplicationRunner runner(ArticleService service) {
        return args -> service.findAll().forEach(System.out::println);
    }
----

